
[functions.rag-process]
enabled = true
verify_jwt = false
import_map = "./functions/rag-process/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/rag-process/index.ts"

[functions.health-check]
verify_jwt = false

[functions.cron-agent]
verify_jwt = false
